### ISSUE TITLE
Just wanted to comment on Notes on Go

### ISSUE THREAD

**Issue by mholt** [brandur/org#6]
Hi!

Great article: https://brandur.org/go - thanks for writing up your experience. Hope you don't mind if I comment on a few things. Feel free to close this issue anytime :smile:

> Dependency management: It took me a while to warm up to Go’s design around dependency management, but not having to run and manage everything through a slow and complex system like Bundler hugely improves the development experience. It also makes it very easy to jump into foreign libraries and examine their implementations when necessary.

Really glad you recognized this. Makes the Go experience much more enjoyable!

> Error handling: I like that generally my programs don’t crash, but dealing with errors requires an incredible level of micro-management. Worse yet, the encouraged patterns of passing errors around through returns can occasionally make it very difficult to identify the original site of a problem.

Returning errors is an elegant way to handle them. Let the error bubble up the stack to the first function that has enough context to handle it properly. If you want to trace its origin, you can wrap each return with something like this:

```go
if err := doSomething(); err != nil {
    return fmt.Errorf("could not do something: %v", err)
}
```

I've found this to be an effective way to handle errors in my own applications, and to know pretty precisely the flow of the program and where the error came from.

> The community: Reading the mailings lists can be still be pretty depressing. Every critique of the language or suggestion for improvement, no matter how valid, is met with a barrage of either “you’re doing it wrongs”, or “only the Go core team that can have thoughts that are worth consideration” Previously this level of zealotry had been reserved for holy crusades and text editors.

You'll find those types anywhere, it's definitely not only from text editor debates. You should try the [Gophers Slack](https://gophersinvite.herokuapp.com/) and the [Go Forum](https://forum.golangbridge.org). Both are great places to be a part of the Go community.

Anyway, hopefully this feedback is helpful. Thanks again for your post!

**Comment by brandur** [comment]
> Great article: https://brandur.org/go - thanks for writing up your experience. Hope you don't mind if I comment on a few things. Feel free to close this issue anytime :smile:

Not at all! Thanks for taking the time to leave feedback.

> Really glad you recognized this. Makes the Go experience much more enjoyable!

+1. After you make it over the initial "this is weird" barrier, I found that it all comes together quite well.

> Returning errors is an elegant way to handle them. Let the error bubble up the stack to the first function that has enough context to handle it properly. If you want to trace its origin, you can wrap each return with something like this:

Yeah, I think this is an area that I may not be 100% grasping yet.

I tried to some degree the approach that you've suggested here but I found that this "breadcrumb style" of error handling to be quite manual. I wanted to tag the errors with things like the module that it came from, which wasn't very friendly to refactoring as these blocks of code get moved around. I also felt like I was just re-inventing a stack trace.

Having the error bubble up to the first level that can properly handle it is a very theoretically elegant idea, but I found in practice that it was often most robust to just have these errors bubble up all the way to a very high level so that you can basically just "restart the world" from a blank slate. This leaves you without a whole bunch of corner case error recovery logic which rarely gets run and which probably won't work the day it does.

In fact, in at least some cases I just allowed errors to bubble up and exit the program and then allow the system's service manager to restart it. Again, not as elegant as the recommended error handling method, but probably okay for the purposes of most users, and _much_ more likely to work the day you need it to.

> You'll find those types anywhere, it's definitely not only from text editor debates. You should try the Gophers Slack and the Go Forum. Both are great places to be a part of the Go community.

Ah yes, totally right. That may have been worded a little too strongly. I found some of the core lists to be particularly bad for it, but of course there are probably lots of more constructive Go communities out there. I'll try these ones. Thanks!
